import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Capstone Auto Parts",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.svg', // default favicon
    shortcut: '/logo.svg',
    apple: '/logo.svg', // apple devices
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-white">
        {children}
      </body>
    </html>
  );
}
